[package]
name = "pwasm-validation"
version = "0.1.0"
authors = ["Pat Hickey <pat@moreproductive.org>"]

[dependencies]
parity-wasm = "0.35"
memory_units = "0.4.0"

[dev-dependencies]
assert_matches = "1.3"
wabt = "0.7"
